# Generated by Django 2.0 on 2021-08-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newu',
            name='img',
            field=models.FileField(default='20191207_081057.jpg', upload_to='img/'),
        ),
    ]
